apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-ms-test-lbascur
  namespace: camp-qa
  labels:
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camp-ms-test-lbascur
  template:
    metadata:
      labels:
        app: camp-ms-test-lbascur
    spec:
      containers:
        - image: us.icr.io/bupa-infra/mesh:0.1.6
          imagePullPolicy: IfNotPresent
          name: aeol-sidecar
          ports:
            - containerPort: 5001
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /go/bin/configurator.yaml
              name: aeol-configmap
              subPath: configurator.yaml
        - env:
            - name: CONFIG
              value: /go/bin/configuration.yaml
          name: camp-ms-test-lbascur
          image: atsuiest/go-test:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      volumes:
        - configMap:
            defaultMode: 420
            name: cp-ms-alerts-qa-sidecar-configmap
          name: aeol-configmap
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - camp-ms-test-lbascur
                topologyKey: 'kubernetes.io/hostname'
