apiVersion: apps/v1
kind: Deployment
metadata:
  name: camp-ms-test-lbascur
  namespace: camp-qa
  labels:
    environment: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camp-ms-test-lbascur
  template:
    metadata:
      labels:
        app: camp-ms-test-lbascur
    spec:
      containers:
        - image: bupacl/arquitectura-mesh:2.1.0
          imagePullPolicy: IfNotPresent
          name: ms-lbascur-mesh
          ports:
            - containerPort: 5001
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /go/bin/configuration.yaml
              mountPropagation: None
              name: mesh-volume
              subPath: configuration.yaml
          env:
            - name: STACKER_CONFIG
              value: /go/bin/configuration.yaml
        - name: camp-ms-test-lbascur
          image: atsuiest/go-test:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      volumes:
        - configMap:
            defaultMode: 420
            name: ms-lbascur-mesh
          name: mesh-volume
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - camp-ms-test-lbascur
                topologyKey: 'kubernetes.io/hostname'
