apiVersion: v1
kind: Service
metadata:
  name: camp-lbascur-svc
  namespace: camp-qa
  labels:
    app: camp-ms-test-lbascur
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5001
  selector:
    app: camp-ms-test-lbascur
