apiVersion: v1
data:
  configuration.yaml: |
    serverport: "5001"
    targetport: "8080"
    middleware:
        secure  : false
        cache   : false
kind: ConfigMap
metadata:
  name: ms-lbascur-mesh
  namespace: camp-qa
